version: '3'

services:
  builder:
    build: './builder'
  apache:
    build: './apache'
    volumes:
      - ./config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./srv:/usr/local/apache2/htdocs/
      - shared-sockets:/var/socks/
    depends_on:
      - builder
  php5:
    build: './php5'
    volumes:
      - ./config/php-fpm.d/:/etc/php-fpm.d
      - ./config/php/:/etc/php/
      - ./srv:/usr/local/apache2/htdocs/
      - shared-sockets:/var/socks/
    depends_on:
      - builder
  modsec:
    build: './modsecurity-spoe'
  haproxy:
    build: './haproxy'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/haproxy:/etc/haproxy:ro
      - ./var/run/haproxy:/var/run/haproxy
      - shared-sockets:/var/socks/
    depends_on:
      - builder
      - apache
      - php5
volumes:
  shared-sockets: